name: Integration Tests

on: [push]

jobs:
#  build-linux:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v2
#        with:
#          java-version: 1.8
#          distribution: adopt
#      - name: Build and run tests
#        run: mvn -B verify
#
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - name: Build and run tests
        run: |
          mvn -B package
          echo %JAVA_HOME%
          dir %JAVA_HOME%
          dir %JAVA_HOME%\bin
          java -jar target\extract-tls-secrets-4.1.0-SNAPSHOT.jar list
